LABEL = 'LABEL'
PHIST_BIN_COUNT = 8

FLOW_STATS_COLUMNS = ['BYTES', 'BYTES_REV', 'LINK_BIT_FIELD', 'PACKETS',
       'PACKETS_REV', 'MQTT_KEEP_ALIVE', 'MQTT_TYPE_CUMULATIVE',
       'DIR_BIT_FIELD', 'MQTT_CONNECTION_FLAGS',
       'MQTT_CONNECTION_RETURN_CODE', 'MQTT_PUBLISH_FLAGS', 'MQTT_VERSION',
       'PROTOCOL', 'TCP_FLAGS', 'TCP_FLAGS_REV',
       'DURATION', 'PPI_LEN', 'PPI_DURATION', 'FLAG_CWR',
       'FLAG_CWR_REV', 'FLAG_ECE', 'FLAG_ECE_REV', 'FLAG_URG', 'FLAG_URG_REV',
       'FLAG_ACK', 'FLAG_ACK_REV', 'FLAG_PSH', 'FLAG_PSH_REV', 'FLAG_RST',
       'FLAG_RST_REV', 'FLAG_SYN', 'FLAG_SYN_REV', 'FLAG_FIN', 'FLAG_FIN_REV',
       'PHIST_SRC_SIZES_0', 'PHIST_SRC_SIZES_1', 'PHIST_SRC_SIZES_2',
       'PHIST_SRC_SIZES_3', 'PHIST_SRC_SIZES_4', 'PHIST_SRC_SIZES_5',
       'PHIST_SRC_SIZES_6', 'PHIST_SRC_SIZES_7', 'PHIST_DST_SIZES_0',
       'PHIST_DST_SIZES_1', 'PHIST_DST_SIZES_2', 'PHIST_DST_SIZES_3',
       'PHIST_DST_SIZES_4', 'PHIST_DST_SIZES_5', 'PHIST_DST_SIZES_6',
       'PHIST_DST_SIZES_7', 'PHIST_SRC_IPT_0', 'PHIST_SRC_IPT_1',
       'PHIST_SRC_IPT_2', 'PHIST_SRC_IPT_3', 'PHIST_SRC_IPT_4',
       'PHIST_SRC_IPT_5', 'PHIST_SRC_IPT_6', 'PHIST_SRC_IPT_7',
       'PHIST_DST_IPT_0', 'PHIST_DST_IPT_1', 'PHIST_DST_IPT_2',
       'PHIST_DST_IPT_3', 'PHIST_DST_IPT_4', 'PHIST_DST_IPT_5',
       'PHIST_DST_IPT_6', 'PHIST_DST_IPT_7']